### ISSUE TITLE
Agency dashboard broken on some links with PRISONS_BUDGET error

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#298]
[Link to logs](https://console.cloud.google.com/logs/query;query=resource.type%20%3D%20%22cloud_run_revision%22%0A%2528resource.labels.service_name%20%3D%20%22justice-counts-web%22%2529%20OR%20%2528resource.labels.service_name%20%3D%20%22justice-counts-agency-dashboard-web%22%2529%0Aresource.labels.location%20%3D%20%22us-central1%22%0Aseverity%3E%3D%22ERROR%22%20severity%3E%3DDEFAULT;cursorTimestamp=2023-01-12T18:35:08.395262Z?project=recidiviz-staging)

Broken URL: https://dash---justice-counts-agency-dashboard-web-qqec6jbn6a-uc.a.run.app/feed/152?system=PRISONS&metric=releases_by_type

I thought we should be filtering out deprecated metrics so I'm not sure what's going on here!
```
Traceback (most recent call last):
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/recidiviz/justice_counts/control_panel/server.py", line 153, in get_feed_for_agency_id
    system_to_filename_to_rows = FeedInterface.get_feed_for_agency_id(
  File "/app/recidiviz/justice_counts/feed.py", line 92, in get_feed_for_agency_id
    system = METRIC_KEY_TO_METRIC[metric_key].system
KeyError: 'PRISONS_BUDGET'
```

**Comment by terryttsai** [comment]
Locally I get a slightly different error:
```
control_panel_backend_1      | Traceback (most recent call last):
control_panel_backend_1      |   File "/app/.venv/lib/python3.9/site-packages/werkzeug/serving.py", line 324, in run_wsgi
control_panel_backend_1      |     execute(self.server.app)
control_panel_backend_1      |   File "/app/.venv/lib/python3.9/site-packages/werkzeug/serving.py", line 313, in execute
control_panel_backend_1      |     application_iter = app(environ, start_response)
control_panel_backend_1      |   File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
control_panel_backend_1      |     return self.wsgi_app(environ, start_response)
control_panel_backend_1      |   File "/app/.venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
control_panel_backend_1      |     return self.app(environ, start_response)
control_panel_backend_1      |   File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
control_panel_backend_1      |     response = self.handle_exception(e)
control_panel_backend_1      |   File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
control_panel_backend_1      |     response = self.full_dispatch_request()
control_panel_backend_1      |   File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
control_panel_backend_1      |     rv = self.handle_user_exception(e)
control_panel_backend_1      |   File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
control_panel_backend_1      |     rv = self.dispatch_request()
control_panel_backend_1      |   File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
control_panel_backend_1      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
control_panel_backend_1      |   File "/app/recidiviz/justice_counts/control_panel/server.py", line 153, in get_feed_for_agency_id
control_panel_backend_1      |     system_to_filename_to_rows = FeedInterface.get_feed_for_agency_id(
control_panel_backend_1      |   File "/app/recidiviz/justice_counts/feed.py", line 110, in get_feed_for_agency_id
control_panel_backend_1      |     metricfile = SYSTEM_METRIC_KEY_AND_DIM_ID_TO_METRICFILE[
control_panel_backend_1      | KeyError: (<System.PRISONS: 'PRISONS'>, 'PRISONS_POPULATION', 'global/gender/restricted')

```

**Comment by terryttsai** [comment]
So running this locally, my guess is that perhaps the individual metric file mappings like `PRISON_METRIC_FILES` are out of date? 

I was able to handle the error above by adding a `population_by_gender` entry in `PRISON_METRIC_FILES` like so:
```
    MetricFile(
        canonical_filename="population_by_gender",
        definition=prisons.daily_population,
        disaggregation=GenderRestricted,
        disaggregation_column_name="gender",
    ),
```

But then I ran into new key errors that these are missing: 
```
control_panel_backend_1      | (<System.PRISONS: 'PRISONS'>, 'PRISONS_ADMISSIONS', 'metric/prisons/offense/type')
control_panel_backend_1      | (<System.PRISONS: 'PRISONS'>, 'PRISONS_POPULATION', 'metric/prisons/offense/type')
```

I made it so that we have these metric file entries but the issue still persists:
```
    MetricFile(
        canonical_filename="admissions_by_type",
        definition=prisons.admissions,
        disaggregation=OffenseType,
        disaggregation_column_name="offense_type",
    ),
    MetricFile(
        canonical_filename="population_by_type",
        definition=prisons.daily_population,
        disaggregation=OffenseType,
        disaggregation_column_name="offense_type",
```

@lilidworkin @nichelle-hall how do I make sure I have the canonical metric files up to date so that we don't get key errors?

**Comment by lilidworkin** [comment]
@terryttsai I'm suspicious that that's the issue, I suspect there's something else going on here, but I'll take a look tomorrow morning! Thanks for looking into it!

**Comment by lilidworkin** [comment]
@nichelle-hall if you have a chance to take a look in the meantime that would be awesome too!

**Comment by lilidworkin** [comment]
@terryttsai one suggestion: if you haven't, you might try debugging with some print/logger statements. You should be able to see the output when running locally. For instance, you know the issue is a KeyError with the dictionary `SYSTEM_METRIC_KEY_AND_DIM_ID_TO_METRICFILE` -- maybe try printing that dictionary to see what keys it *does* have?

**Comment by lilidworkin** [comment]
AH I just realized this is an error when downloading the data (i.e. feed) not when rendering the dashboard! Oh no wonder that's broken, I haven't touched that in forever. I think you don't have to worry about this @terryttsai , I can handle it :)
